//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class asset_details
    {
        public int asset_id { get; set; }
        public string serial_number { get; set; }
        public string model { get; set; }
        public string brand { get; set; }
        public string imei { get; set; }
        public string description { get; set; }
        [DataType(DataType.Date)]
        public string purchase_date { get; set; }
        public int asset_type_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> cost_id { get; set; }
    
        public virtual asset_type asset_type { get; set; }
        public virtual cost_details cost_details { get; set; }
        public virtual employee employee { get; set; }
    }
}
