//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assetManagementEntities : DbContext
    {
        public assetManagementEntities()
            : base("name=assetManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asset_details> asset_details { get; set; }
        public virtual DbSet<asset_type> asset_type { get; set; }
        public virtual DbSet<cost_details> cost_details { get; set; }
        public virtual DbSet<cost_type> cost_type { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<software_details> software_details { get; set; }
    }
}
